// AUTO-GENERATED BY npm run generate:registry-shells
import { Title } from "@solidjs/meta";
import { RegistryPageShell } from "~/components/registry-page-shell";
import { DashboardSidebarWorkspace } from "~/components/registry/tier-3/app-shells-dashboards/dashboard-sidebar-workspace";
import { registryItemBySlug } from "~/lib/registry";

export default function DashboardSidebarWorkspacePage() {
  return (
    <>
      <Title>DashboardSidebarWorkspace | Stylyf</Title>
      <RegistryPageShell item={registryItemBySlug["dashboard-sidebar-workspace"]}>
        <DashboardSidebarWorkspace />
      </RegistryPageShell>
    </>
  );
}
