export function renderGeneratedStorageModule() {
  return [
    'import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";',
    'import { getSignedUrl } from "@aws-sdk/s3-request-presigner";',
    'import { env } from "~/lib/env";',
    "",
    "export type UploadIntent = {",
    "  key: string;",
    "  contentType: string;",
    "  expiresIn?: number;",
    "};",
    "",
    "function parseForcePathStyle(value?: string) {",
    '  return value === "true" || value === "1";',
    "}",
    "",
    "export function getStorageClient() {",
    "  return new S3Client({",
    "    region: env.S3_REGION,",
    "    bucketEndpoint: false,",
    "    endpoint: env.S3_ENDPOINT || undefined,",
    "    forcePathStyle: parseForcePathStyle(env.S3_FORCE_PATH_STYLE),",
    "    credentials: {",
    "      accessKeyId: env.S3_ACCESS_KEY_ID,",
    "      secretAccessKey: env.S3_SECRET_ACCESS_KEY,",
    "    },",
    "  });",
    "}",
    "",
    "export async function createPresignedUpload(input: UploadIntent) {",
    "  const client = getStorageClient();",
    "  const expiresIn = input.expiresIn ?? 900;",
    "  const command = new PutObjectCommand({",
    "    Bucket: env.S3_BUCKET,",
    "    Key: input.key,",
    "    ContentType: input.contentType,",
    "  });",
    "  const url = await getSignedUrl(client, command, { expiresIn });",
    "  return {",
    "    method: 'PUT' as const,",
    "    url,",
    "    key: input.key,",
    "    bucket: env.S3_BUCKET,",
    "    expiresIn,",
    "    headers: {",
    '      "content-type": input.contentType,',
    "    },",
    "  };",
    "}",
    "",
    "export async function deleteObject(key: string) {",
    "  const client = getStorageClient();",
    "  await client.send(",
    "    new DeleteObjectCommand({",
    "      Bucket: env.S3_BUCKET,",
    "      Key: key,",
    "    }),",
    "  );",
    "}",
    "",
    "export function buildObjectUrl(key: string) {",
    "  if (env.S3_PUBLIC_BASE_URL) {",
    "    return new URL(key, env.S3_PUBLIC_BASE_URL.endsWith('/') ? env.S3_PUBLIC_BASE_URL : `${env.S3_PUBLIC_BASE_URL}/`).toString();",
    "  }",
    "",
    "  if (env.S3_ENDPOINT) {",
    "    const base = env.S3_ENDPOINT.replace(/\\/$/, '');",
    "    const prefix = parseForcePathStyle(env.S3_FORCE_PATH_STYLE) ? `${env.S3_BUCKET}/` : '';",
    "    return `${base}/${prefix}${key}`;",
    "  }",
    "",
    "  return `https://${env.S3_BUCKET}.s3.${env.S3_REGION}.amazonaws.com/${key}`;",
    "}",
    "",
  ].join("\n");
}
