-- Generated by Stylyf CLI
-- Apply this alongside supabase/schema.sql for resource-driven row level security defaults.
-- Membership tables are readable by their own users but write-locked by default.
-- App-owned admin membership provisioning should happen through trusted server code or Supabase dashboard operations.

alter table if exists public."projects" enable row level security;
drop policy if exists "projects_select" on public."projects";
create policy "projects_select" on public."projects" for select to anon, authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "projects_insert" on public."projects";
create policy "projects_insert" on public."projects" for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "projects_update" on public."projects";
create policy "projects_update" on public."projects" for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id") with check ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "projects_delete" on public."projects";
create policy "projects_delete" on public."projects" for delete to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");

alter table if exists public."agent_events" enable row level security;
drop policy if exists "agent_events_select" on public."agent_events";
create policy "agent_events_select" on public."agent_events" for select to anon, authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "agent_events_insert" on public."agent_events";
create policy "agent_events_insert" on public."agent_events" for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "agent_events_update" on public."agent_events";
create policy "agent_events_update" on public."agent_events" for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id") with check ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");
drop policy if exists "agent_events_delete" on public."agent_events";
create policy "agent_events_delete" on public."agent_events" for delete to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = "owner_id");

-- Attachment metadata policies generated by Stylyf CLI
alter table if exists public."projects_assets" enable row level security;
drop policy if exists "projects_assets_select" on public."projects_assets";
create policy "projects_assets_select" on public."projects_assets" for select to anon, authenticated using ("resource_id" in (select "id" from public."projects" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "projects_assets_insert" on public."projects_assets";
create policy "projects_assets_insert" on public."projects_assets" for insert to authenticated with check ("resource_id" in (select "id" from public."projects" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "projects_assets_update" on public."projects_assets";
create policy "projects_assets_update" on public."projects_assets" for update to authenticated using ("resource_id" in (select "id" from public."projects" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id")) with check ("resource_id" in (select "id" from public."projects" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "projects_assets_delete" on public."projects_assets";
create policy "projects_assets_delete" on public."projects_assets" for delete to authenticated using ("resource_id" in (select "id" from public."projects" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));

alter table if exists public."agent_events_assets" enable row level security;
drop policy if exists "agent_events_assets_select" on public."agent_events_assets";
create policy "agent_events_assets_select" on public."agent_events_assets" for select to anon, authenticated using ("resource_id" in (select "id" from public."agent_events" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "agent_events_assets_insert" on public."agent_events_assets";
create policy "agent_events_assets_insert" on public."agent_events_assets" for insert to authenticated with check ("resource_id" in (select "id" from public."agent_events" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "agent_events_assets_update" on public."agent_events_assets";
create policy "agent_events_assets_update" on public."agent_events_assets" for update to authenticated using ("resource_id" in (select "id" from public."agent_events" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id")) with check ("resource_id" in (select "id" from public."agent_events" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
drop policy if exists "agent_events_assets_delete" on public."agent_events_assets";
create policy "agent_events_assets_delete" on public."agent_events_assets" for delete to authenticated using ("resource_id" in (select "id" from public."agent_events" where (select auth.uid()) is not null and (select auth.uid()) = "owner_id"));
