-- Generated by Stylyf CLI
-- Apply this in the Supabase SQL editor or through the Supabase CLI when bootstrapping the hosted database path.

create table if not exists public."projects" (
  "name" text not null,
  "slug" text unique not null,
  "status" text not null,
  "summary" text,
  "workspacePath" text,
  "previewUrl" text,
  "githubRepoFullName" text,
  "lastPushedSha" text,
  "id" uuid primary key default gen_random_uuid(),
  "owner_id" uuid not null,
  "created_at" timestamptz not null default timezone('utc'::text, now()),
  "updated_at" timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public."projects_assets" (
  "id" uuid primary key default gen_random_uuid(),
  "resource_id" uuid not null,
  "attachment_name" text not null,
  "bucket_alias" text not null,
  "object_key" text unique not null,
  "object_url" text,
  "file_name" text,
  "content_type" text,
  "file_size" integer,
  "kind" text not null,
  "status" text not null,
  "metadata" jsonb,
  "replaced_by_asset_id" uuid,
  "deleted_at" timestamptz,
  "created_at" timestamptz not null default timezone('utc'::text, now()),
  "updated_at" timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public."agent_events" (
  "type" text not null,
  "payload" jsonb,
  "id" uuid primary key default gen_random_uuid(),
  "owner_id" uuid not null,
  "created_at" timestamptz not null default timezone('utc'::text, now()),
  "updated_at" timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public."agent_events_assets" (
  "id" uuid primary key default gen_random_uuid(),
  "resource_id" uuid not null,
  "attachment_name" text not null,
  "bucket_alias" text not null,
  "object_key" text unique not null,
  "object_url" text,
  "file_name" text,
  "content_type" text,
  "file_size" integer,
  "kind" text not null,
  "status" text not null,
  "metadata" jsonb,
  "replaced_by_asset_id" uuid,
  "deleted_at" timestamptz,
  "created_at" timestamptz not null default timezone('utc'::text, now()),
  "updated_at" timestamptz not null default timezone('utc'::text, now())
);

